### PR TITLE
Feature: Add Cloud Four Events CPT

### PR DESCRIPTION
**Pull request by mrgerardorodriguez**
Re: https://trello.com/c/wr9g3Llv/199-set-up-custom-post-types

## Overview

This PR will add the Cloud Four Event Custom Post Type.

## Details

I'd like to get this in front of other's eyes to review. There is one item that will need to be adjusted, but if folks are okay with it, we can submit a separate PR to handle the TODO item. 

The PR changes include:
- Adds a base Cloud Four CPT class
- Adds a Cloud Four Event CPT class which extends the base class
- Adds require for C4 Event CPT in `functions.php`
- Calls the C4 Event CPT setup function in pre-existing `register_post_types()` method

### TODOS
- The `event_date` custom field needs to be revisited. Currently, it is using a calendar picker, but this limits the selection to a single day at the moment. More research needs to be done around this. Can we change it to use a range of dates? If not, what other input field types make sense? We'll have to refer to the [available ACF custom field types](https://www.advancedcustomfields.com/resources/#field-types) to help answer this question.

### Screenshots

add-new-event

add-new-event-date

select-speakers

---

cc: @erikjung @tylersticka @aileenjeffries @grigs

### CODE REVIEW

**Comment by tylersticka** [comment]
> More research needs to be done around this. Can we change it to use a range of dates? If not, what other input field types make sense?

I imagine either a numeric field that detaults to `1` for the event length in days, or a second optional date picker for the end date.

**Comment by mrgerardorodriguez** [comment]
Oh, great ideas @tylersticka! 

> or a second optional date picker for the end date

I kinda like this idea. :)

**Comment by mrgerardorodriguez** [comment]
Per your suggestion @tylersticka, I've added a "start" and "end" date.

end-date

**Comment by tylersticka** [comment]
@mrgerardorodriguez Neat!

I'm not sure when I'll have a chance to review this PR since I haven't set up my environment yet. I looked through the code and didn't see anything amiss, but if you need more concrete review, let me know and I'll try to reprioritize.

**Comment by mrgerardorodriguez** [comment]
Thanks @tylersticka! 😄 

I'll leave it open through tomorrow. It doesn't have to be reviewed today (especially since my work day is over now). At some point, it would be nice to get someone (doesn't have to be @tylersticka, could be @erikjung, @megnotarte, @grigs or anyone really) to set up the local dev environment to start testing things. 

For this PR, though, it _is not_ required. :) 

Eventually (maybe next week?) when we get folks testing locally, if things need to be modified, we can address them at that point. 😉

**Comment by erikjung** [comment]
@mrgerardorodriguez 

I was able to test this out locally. It took me a bit to figure out which plugins needed to be activated in order to get the "Events" type to show in my sidebar after switching branches.

It appears to work just fine (I created an event).

👍 

screen shot 2016-06-23 at 2 46 44 pm

**Pull request merged**
