### PR TITLE
Feature: Add Cloud Four Case Study CPT

### PR DESCRIPTION
**Pull request by mrgerardorodriguez**
Re: https://trello.com/c/wr9g3Llv/199-set-up-custom-post-types

## Overview

This PR adds a Cloud Four Case Study custom post type.

### Details

The CPT fields include:
- Project Title
- Case Study Tagline (text, required)
- Phone Frame Image (image, required)
- Browser Frame Image (image, required)
- Short Description (wysiwyg, required)
- Long Description (wysiwyg, required)

### Screenshot

add-new-case-study

---

cc: @erikjung @tylersticka @aileenjeffries @nicolemors

### CODE REVIEW

**Comment by mrgerardorodriguez** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;wr9g3Llv&#x2F;199-set-up-custom-post-types"> Set up custom post types</a>

**Comment by tylersticka** [comment]
I find the "phone frame image" and "browser frame image" confusing. They're both likely screenshots of browsers, and neither contain a frame (the frame part is in the SVG presentation).

Maybe just "Narrow Screenshot" and "Wide Screenshot"? Or "Small Screenshot" and "Large Screenshot"?

**Comment by mrgerardorodriguez** [comment]
Thanks for the feedback @tylersticka!

> Maybe just "Narrow Screenshot" and "Wide Screenshot"? Or "Small Screenshot" and "Large Screenshot"?

How about "Narrow Viewport Screenshot" and "Wide Viewport Screenshot"? Would that work?

**Comment by tylersticka** [comment]
> How about "Narrow Viewport Screenshot" and "Wide Viewport Screenshot"? Would that work?

Sure!

**Comment by mrgerardorodriguez** [comment]
Alrighty @tylersticka! I've updated the wording. How does this look?

add-new-case-study

**Comment by mrgerardorodriguez** [comment]
Another PR you can help review @saralohr. 😉

**Comment by saralohr** [comment]
Looks good!

**Pull request merged**
